function Sidebar({ result, conversations, activeId, view, collapsed, onToggle, onNewChat, onOpenConversation, onRename, onDelete, onNavigate, isOpen, onClose }) {
  const decision = result?.gate_decision || {}
  const groups = groupConversations(conversations)
  return <aside className={`sidebar ${isOpen ? 'open' : ''} ${collapsed ? 'collapsed' : ''}`}>
    <div className="sidebar-top"><div className="sidebar-brand"><span className="brand-mark">GO</span><span className="sidebar-copy">GateOrchestra</span></div><button className="sidebar-toggle" type="button" onClick={onToggle} aria-label="Toggle sidebar">☰</button><button className="icon-button sidebar-close" type="button" onClick={onClose} aria-label="Close sidebar">x</button></div>
    <button className="new-chat-button" type="button" onClick={onNewChat}><span>+</span><span className="sidebar-copy"> New Chat</span></button>
    <nav className="sidebar-nav" aria-label="Workspace">{['plugins', 'library', 'projects', 'evolution', 'benchmarks', 'schedules'].map((item) => <button key={item} className={view === item ? 'nav-active' : ''} type="button" onClick={() => onNavigate(item)}><span>{iconFor(item)}</span><span className="sidebar-copy"> {titleFor(item)}</span></button>)}</nav>
    <div className="recent-chats sidebar-copy"><p className="sidebar-label">Recent Chats</p>{Object.entries(groups).map(([group, items]) => items.length ? <div key={group}><p className="history-group">{group}</p>{items.map((conversation) => <HistoryItem key={conversation.id} conversation={conversation} active={conversation.id === activeId} onOpen={onOpenConversation} onRename={onRename} onDelete={onDelete} />)}</div> : null)}{!conversations.length ? <p className="history-empty">Your conversations will appear here.</p> : null}</div>
    <div className="sidebar-status"><p className="sidebar-label sidebar-copy">System Status</p><div className="connection-status"><span className="status-dot" /><span className="sidebar-copy">Ready</span></div><div className="sidebar-metrics sidebar-copy"><Metric label="Token Budget" value={decision.token_budget_cap ?? '--'} /><Metric label="Token Spent" value={result?.tokens_spent ?? '--'} /><Metric label="Current Gate" value={decision.decision || '--'} /><Metric label="Agents" value={result ? '4' : '--'} /></div></div>
    <div className="profile-wrap"><button className="profile-button" type="button" onClick={(event) => event.currentTarget.nextElementSibling.classList.toggle('visible')}>👤 <span className="sidebar-copy">Profile</span></button><div className="profile-popover"><button type="button">Profile</button><button type="button">Settings</button><button type="button">Usage</button><button type="button">Log out</button></div></div>
  </aside>
}
function HistoryItem({ conversation, active, onOpen, onRename, onDelete }) { const menu = (event) => { event.stopPropagation(); const action = window.prompt('Type rename or delete', 'rename'); if (action === 'delete') onDelete(conversation.id); if (action === 'rename') { const title = window.prompt('Conversation name', conversation.title); if (title?.trim()) onRename(conversation.id, title.trim()) } }; return <button className={`chat-history-item ${active ? 'active' : ''}`} type="button" onClick={() => onOpen(conversation.id)}><span className="history-dot" /><span className="history-title">{conversation.title}</span><span className="history-actions" onClick={menu} role="button" tabIndex="0" aria-label="Conversation actions">...</span></button> }
function groupConversations(conversations) { const groups = { Today: [], Yesterday: [], 'Previous 7 days': [], Older: [] }; const now = new Date(); conversations.slice().sort((a, b) => new Date(b.updatedAt) - new Date(a.updatedAt)).forEach((conversation) => { const days = Math.floor((now - new Date(conversation.updatedAt)) / 86400000); groups[days < 1 ? 'Today' : days < 2 ? 'Yesterday' : days < 7 ? 'Previous 7 days' : 'Older'].push(conversation) }); return groups }
function titleFor(item) { return item.replace(/(^|[- ])\w/g, (match) => match.toUpperCase()) }
function iconFor(item) { return { plugins: '🔌', library: '📚', projects: '▣', evolution: '🧬', benchmarks: '📊', schedules: '📅' }[item] }
function Metric({ label, value }) { return <div className="sidebar-metric"><span>{label}</span><strong>{value}</strong></div> }
export default Sidebar
